# -*- coding: utf-8 -*-
"""Open-source.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17m37QYMG4LO6oyMdkTxNtFzQW8uWDd_-

## **Teacher model**
### Version v1.3.1. [HuggingFace Link](https://huggingface.co/protonx-models/protonx-legal-tc)

Điểm nhấn
- Chiều dài ngữ cảnh: 160 tokens
- Sửa đầu ra của Paddle-OCR VL
- Sửa hiện tượng ảo giác khi câu đầu vào dài

**Chú ý**: Chiều dài tối đa sinh tốt của model là 160 tokens (Khoảng 130 từ), nên nếu văn bản của bạn dài bạn hay chia nhỏ thành từng phần và sử dụng mô hình

Demo sửa Paddle OCR VL
"""

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_path = "protonx-models/protonx-legal-tc"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSeq2SeqLM.from_pretrained(model_path)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

examples = [
    "THÉ SINH VIEN",
    "DAI Hoc ACB",
    "QUY ĐỊNH CHI TI3T VÀ HƯỚNG DaN MỘT SỐ ĐIeU CỦA NGHỊ ĐiNH SỐ 85/2016/NĐ-CP NGÀY 01/7/2016 CỦA CHÍNH PHỦ VỀ BẢO ĐẢM AN TOÀN HỆ THỐNG THÔNG TIN THEO CẤP ĐỘ",
    "thut dé tao lruè duut llt v tao di",
    "truyèn dǎn ké ni qu téhē thng v tnh thōng truyèn dan cùa doanh ngiēp",
    "NHUNGQUYDINHCHUNG",
    "Dièu 1.Pham vi dièu chinh",
    "an toàn xa hi tēn khōng gian mang； trách nhiēm cùa co quantō chúr cá nhan",
    "gay phuong hai dén an ninh quc gia tra tr an toàn x hi quyèn và li h",
    "Căn cứ Nghị định so 85/2016/NĐ-CP ngày 01 tháng 7 năm 2016 của Chính phủ về bao đam an toàn hệ thống thông tin theo cấp độ;",
    "Căn cứ Nghị định số 48/2022/NĐ-CP ngày 26 tháng 7 năm 2022 của Chính phủ quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Bộ Thông tin và Truyền thông;",
    "Bộ trưởng Bộ Thông tin và Truyền thông ban hành Thông tư quy định chi tiết và hướng dẫn một số điều của Nghị định số 85/2016/NĐ-CP ngày 01 tháng 7 năm 2016 về bảo đảm an toàn hệ thống thông tin theo cấp độ."
    "NGHỊ ĐiNH SỐ 85/2016/NĐ-CP NGÀY 01/7/2016",
    "hom nay toi den vanphong de nop ho so nhung gap tinhtrang may in bi loi nen toi phai doi rat lau, nhanvien bao rang he thong dang capnhat nen moi nguoi thongcam, nhung toi van thay rat bat tien va mat nhieu thoi gian cho viec nay.",
    "Bộ trưởng Bộ Thông tin và Truyền thông ban hành Thông tư quy định chi tiết và hướng dẫn một số điều của Nghị định số 85/2016/NĐ-CP ngày 01 tháng 7 năm 2016 về bảo đảm an toàn hệ thống thông tin theo cấp độ.",
    "Căn cứ Luat An toan thông tin mạng ngay 19 tháng 11 nom 2015",
    "của Chính phủ về bao đam an toàn hệ thống thông tin theo cấp độ",
    "Am Thuc Thai Linh",
    "Nhà nuoc cong hoa xa hoi chu nghia Viet nam",
    "Luāt này quy dinh vè hoat dōng bào vē an ninh quóc gia và bào dàm trāt tr",
    "an toàn xa hi tēn khōng gian mang； trách nhiēm cùa co quantō chúr cá nhan",
    "5.Co sò ha tàng khōng gian mang quōc gia là hē thng c s vt chák",
    "cung cáp dich v trēn mang viēn thōngmang Interne các dich v gia tǎng trēn",
    "an ninh mang",
    "thut dé tao lruè duut llt v tao di",
    "truyen thong trong nuoc cho rang",
    "can cu bo luat lao dong 2019 va cac van ban huong dan thuc hien.",
    "Nguyên Bá Ngọc",
]

max_tokens = 160

for text in examples:
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=max_tokens
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            num_beams=10,
            num_return_sequences=1,     # <- return all beams
            max_new_tokens=max_tokens,
            early_stopping=True,
            return_dict_in_generate=True,  # <- return full dict
            output_scores=True             # <- include beam scores
        )

    sequences = outputs.sequences
    scores = outputs.sequences_scores

    print(f"Input: {text}")

    for i, (seq, score) in enumerate(zip(sequences, scores)):
        decoded = tokenizer.decode(seq, skip_special_tokens=True)
        # print(f"Beam {i+1} | Score: {float(score):.4f}")
        print(f"Output: {decoded}")
        print("-" * 40)

"""Demo sửa các dữ liệu khác"""

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_path = "protonx-models/protonx-legal-tc"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSeq2SeqLM.from_pretrained(model_path)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

examples = [
    "QUY ĐỊNH CHI TI3T VÀ HƯỚNG DaN MỘT SỐ ĐIeU CỦA NGHỊ ĐiNH SỐ 85/2016/NĐ-CP NGÀY 01/7/2016 CỦA CHÍNH PHỦ VỀ BẢO ĐẢM AN TOÀN HỆ THỐNG THÔNG TIN THEO CẤP ĐỘ",
    "thut dé tao lruè duut llt v tao di",
    "truyèn dǎn ké ni qu téhē thng v tnh thōng truyèn dan cùa doanh ngiēp",
    "NHUNGQUYDINHCHUNG",
    "Dièu 1.Pham vi dièu chinh",
    "an toàn xa hi tēn khōng gian mang； trách nhiēm cùa co quantō chúr cá nhan",
    "gay phuong hai dén an ninh quc gia tra tr an toàn x hi quyèn và li h",
    "Căn cứ Nghị định so 85/2016/NĐ-CP ngày 01 tháng 7 năm 2016 của Chính phủ về bao đam an toàn hệ thống thông tin theo cấp độ;",
    "Căn cứ Nghị định số 48/2022/NĐ-CP ngày 26 tháng 7 năm 2022 của Chính phủ quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Bộ Thông tin và Truyền thông;",
    "Bộ trưởng Bộ Thông tin và Truyền thông ban hành Thông tư quy định chi tiết và hướng dẫn một số điều của Nghị định số 85/2016/NĐ-CP ngày 01 tháng 7 năm 2016 về bảo đảm an toàn hệ thống thông tin theo cấp độ."
    "NGHỊ ĐiNH SỐ 85/2016/NĐ-CP NGÀY 01/7/2016",
    "hom nay toi den vanphong de nop ho so nhung gap tinhtrang may in bi loi nen toi phai doi rat lau, nhanvien bao rang he thong dang capnhat nen moi nguoi thongcam, nhung toi van thay rat bat tien va mat nhieu thoi gian cho viec nay.",
    "Bộ trưởng Bộ Thông tin và Truyền thông ban hành Thông tư quy định chi tiết và hướng dẫn một số điều của Nghị định số 85/2016/NĐ-CP ngày 01 tháng 7 năm 2016 về bảo đảm an toàn hệ thống thông tin theo cấp độ.",
    "Căn cứ Luat An toan thông tin mạng ngay 19 tháng 11 nom 2015",
    "của Chính phủ về bao đam an toàn hệ thống thông tin theo cấp độ",
    "Am Thuc Thai Linh",
    "Nhà nuoc cong hoa xa hoi chu nghia Viet nam",
    "Luāt này quy dinh vè hoat dōng bào vē an ninh quóc gia và bào dàm trāt tr",
    "an toàn xa hi tēn khōng gian mang； trách nhiēm cùa co quantō chúr cá nhan",
    "5.Co sò ha tàng khōng gian mang quōc gia là hē thng c s vt chák",
    "cung cáp dich v trēn mang viēn thōngmang Interne các dich v gia tǎng trēn",
    "an ninh mang",
    "thut dé tao lruè duut llt v tao di",
    "truyen thong trong nuoc cho rang",
    "can cu bo luat lao dong 2019 va cac van ban huong dan thuc hien.",
    "Nguyên Bá Ngọc",
]

for text in examples:
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=128
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            num_beams=10,
            num_return_sequences=1,     # <- return all beams
            max_new_tokens=128,
            early_stopping=True,
            return_dict_in_generate=True,  # <- return full dict
            output_scores=True             # <- include beam scores
        )

    sequences = outputs.sequences
    scores = outputs.sequences_scores

    print(f"\n==== Input: {text} ====\n")

    for i, (seq, score) in enumerate(zip(sequences, scores)):
        decoded = tokenizer.decode(seq, skip_special_tokens=True)
        # print(f"Beam {i+1} | Score: {float(score):.4f}")
        print(decoded)
        print("-" * 40)

"""## **Student model**
### Version v1.3.1

**Chú ý**: Chiều dài tối đa sinh tốt của model là 128 tokens (Khoảng 100 từ), nên nếu văn bản của bạn dài bạn hay chia nhỏ thành từng phần và sử dụng mô hình
"""

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_path = "protonx-models/distilled-protonx-legal-tc"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSeq2SeqLM.from_pretrained(model_path)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

examples = [
    "Căn cứ Luat An toan thông tin mạng ngay 19 tháng 11 nom 2015",
]

for text in examples:
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=128
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            num_beams=10,
            num_return_sequences=5,     # <- return all beams
            max_new_tokens=256,
            early_stopping=True,
            return_dict_in_generate=True,  # <- return full dict
            output_scores=True             # <- include beam scores
        )

    sequences = outputs.sequences
    scores = outputs.sequences_scores

    print(f"\n==== Input: {text} ====\n")

    for i, (seq, score) in enumerate(zip(sequences, scores)):
        decoded = tokenizer.decode(seq, skip_special_tokens=True)
        print(f"Beam {i+1} | Score: {float(score):.4f}")
        print(decoded)
        print("-" * 40)

stro = "QUY ĐỊNH CHI TI3T VÀ HƯỚNG DaN MỘT SỐ ĐIeU CỦA NGHỊ ĐiNH SỐ 85/2016/NĐ-CP NGÀY 01/7/2016 CỦA CHÍNH PHỦ VỀ BẢO ĐẢM AN TOÀN HỆ THỐNG THÔNG TIN THEO CẤP ĐỘ"

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# -----------------------------
# Load model + tokenizer
# -----------------------------
model_path = "protonx-models/protonx-legal-tc"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSeq2SeqLM.from_pretrained(model_path)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()


# -----------------------------
# Decode a single chunk (Top-1 beam only)
# -----------------------------
def decode_a_text(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=256
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            num_beams=4,
            num_return_sequences=1,
            max_new_tokens=256,
            early_stopping=True,
        )

    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return decoded


# -----------------------------
# Split into word chunks (24 words)
# -----------------------------
def split_into_word_chunks(text, chunk_size=24):
    words = text.split()
    return [
        " ".join(words[i:i+chunk_size])
        for i in range(0, len(words), chunk_size)
    ]


# -----------------------------
# Decode long text (24-word chunks)
# -----------------------------
def decode_large_text(full_text, chunk_size=12):

    chunks = split_into_word_chunks(full_text, chunk_size)
    print(f"\nTotal chunks: {len(chunks)}")
    print("=" * 50)

    decoded_all = []

    for idx, chunk in enumerate(chunks, 1):
        print(f"\n### Decoding chunk {idx}/{len(chunks)}")
        print(f"Chunk: {chunk}")

        best_decoded = decode_a_text(chunk)
        print(f"→ Decoded: {best_decoded}")

        decoded_all.append(best_decoded)

    final_output = " ".join(decoded_all).strip()
    return final_output


# -----------------------------
# Example usage
# -----------------------------
if __name__ == "__main__":
    text = "QUY ĐỊNH CHI TI3T VÀ HƯỚNG DaN MỘT SỐ ĐIeU CỦA NGHỊ ĐiNH SỐ 85/2016/NĐ-CP NGÀY 01/7/2016 CỦA CHÍNH PHỦ VỀ BẢO ĐẢM AN TOÀN HỆ THỐNG THÔNG TIN THEO CẤP ĐỘ"

    result = decode_large_text(text)

    print("\n====================== FINAL OUTPUT ======================")
    print(result)

"""## **Nano model**
### Version v1.3.1
"""

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_path = "protonx-models/nano-protonx-legal-tc"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSeq2SeqLM.from_pretrained(model_path)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

examples = [
    "Căn cứ Luat An toan thông tin mạng ngay 19 tháng 11 nom 2015;",
    "can cu bo luat lao dong 2019 va cac van ban huong dan thuc hien.",
    "Toi di hoc",
    "Khiem ton",
    "QUY ĐỊNH CHI TI3T VÀ HƯỚNG DaN MỘT SỐ ĐIeU CỦA NGHỊ ĐiNH SỐ 85/2016/NĐ-CP NGÀY 01/7/2016 CỦA CHÍNH PHỦ VỀ BẢO ĐẢM AN TOÀN HỆ THỐNG THÔNG TIN THEO CẤP ĐỘ.",
    "thut dé tao lruè duut llt v tao di",
    "truyèn dǎn ké ni qu téhē thng v tnh thōng truyèn dan cùa doanh ngiēp",
    "NHUNGQUYDINHCHUNG",
    "Dièu 1.Pham vi dièu chinh",
    "an toàn xa hi tēn khōng gian mang； trách nhiēm cùa co quantō chúr cá nhan",
    "gay phuong hai dén an ninh quc gia tra tr an toàn x hi quyèn và li h",
    "Căn cứ Nghị định so 85/2016/NĐ-CP ngày 01 tháng 7 năm 2016 của Chính phủ về bao đam an toàn hệ thống thông tin theo cấp độ;",
    "Căn cứ Nghị định số 48/2022/NĐ-CP ngày 26 tháng 7 năm 2022 của Chính phủ quy định chức năng, nhiệm vụ, quyền hạn và cơ cấu tổ chức của Bộ Thông tin và Truyền thông;",
    "Bộ trưởng Bộ Thông tin và Truyền thông ban hành Thông tư quy định chi tiết và hướng dẫn một số điều của Nghị định số 85/2016/NĐ-CP ngày 01 tháng 7 năm 2016 về bảo đảm an toàn hệ thống thông tin theo cấp độ."
    "NGHỊ ĐiNH SỐ 85/2016/NĐ-CP NGÀY 01/7/2016",
    "hom nay toi den vanphong de nop ho so nhung gap tinhtrang may in bi loi nen toi phai doi rat lau, nhanvien bao rang he thong dang capnhat nen moi nguoi thongcam, nhung toi van thay rat bat tien va mat nhieu thoi gian cho viec nay.",
    "Bộ trưởng Bộ Thông tin và Truyền thông ban hành Thông tư quy định chi tiết và hướng dẫn một số điều của Nghị định số 85/2016/NĐ-CP ngày 01 tháng 7 năm 2016 về bảo đảm an toàn hệ thống thông tin theo cấp độ.",
    "Căn cứ Luat An toan thông tin mạng ngay 19 tháng 11 nom 2015",
    "của Chính phủ về bao đam an toàn hệ thống thông tin theo cấp độ",
    "Am Thuc Thai Linh",
    "Nhà nuoc cong hoa xa hoi chu nghia Viet nam",
    "Luāt này quy dinh vè hoat dōng bào vē an ninh quóc gia và bào dàm trāt tr",
    "an toàn xa hi tēn khōng gian mang； trách nhiēm cùa co quantō chúr cá nhan",
    "5.Co sò ha tàng khōng gian mang quōc gia là hē thng c s vt chák",
    "cung cáp dich v trēn mang viēn thōngmang Interne các dich v gia tǎng trēn",
    "an ninh mang",
    "thut dé tao lruè duut llt v tao di",
    "truyen thong trong nuoc cho rang",
    "can cu bo luat lao dong 2019 va cac van ban huong dan thuc hien.",
    "Nguyên Bá Ngọc",
]

max_tokens = 160

for text in examples:
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=max_tokens
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            num_beams=10,
            num_return_sequences=1,     # <- return all beams
            max_new_tokens=max_tokens,
            early_stopping=True,
            return_dict_in_generate=True,  # <- return full dict
            output_scores=True             # <- include beam scores
        )

    sequences = outputs.sequences
    scores = outputs.sequences_scores

    print(f"Input: {text}")

    for i, (seq, score) in enumerate(zip(sequences, scores)):
        decoded = tokenizer.decode(seq, skip_special_tokens=True)
        # print(f"Beam {i+1} | Score: {float(score):.4f}")
        print(f"Output: {decoded}")
        print("-" * 40)

